# Generated by Django 6.0.6 on 2026-06-07 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookmark",
            name="notes",
        ),
        migrations.AddField(
            model_name="bookmark",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="bookmark",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
