[project]
name = "personal-knowledge-bank"
version = "0.1.0"
description = "Inventory system with Authentication and Authourization"
authors = [
    {name = "kaggwe-marvin",email = "129196464+kaggwe-marvin@users.noreply.github.com"}
]
requires-python = ">=3.12,<4.0"
dependencies = [
    "django (>=6.0.6,<7.0.0)",
    "djangorestframework (>=3.17.2,<4.0.0)",
    "django-redis (>=7.0.0,<8.0.0)",
    "django-environ (>=0.13.0,<0.14.0)",
    "python-dotenv (>=1.2.2,<2.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "django-types (>=0.24.0,<0.25.0)",
    "django-stubs (>=6.0.5,<7.0.0)",
    "black (>=26.5.1,<27.0.0)",
    "pytest (>=9.0.3,<10.0.0)",
    "pytest-django (>=4.12.0,<5.0.0)",
    "mypy (>=2.1.0,<3.0.0)"
]

[tool.poetry]
package-mode = false

[tool.black]
line-length = 88
target-version = ['py311']

[tool.mypy]
plugins = ["mypy_django_plugin.main"]
strict = true

[tool.django-stubs]
django_settings_module = "config.settings"

[[tool.mypy.overrides]]
module = "manage"
ignore_errors = true

[[tool.mypy.overrides]]
module = "rest_framework.*"
ignore_missing_imports = true

